const { ImapFlow } = require('imapflow');
const { simpleParser } = require('mailparser');
const nodemailer = require('nodemailer');
const crypto = require('crypto');
const aiService = require('./aiService');
const Customer = require('../models/Customer');
const Enquiry = require('../models/Enquiry');
const User = require('../models/User');
const Task = require('../models/Task');
const FollowUp = require('../models/FollowUp');
const EmailMessage = require('../models/EmailMessage');
const ProcessedEmail = require('../models/ProcessedEmail');
const Attachment = require('../models/Attachment');
const { getNextSequenceValue } = require('../utils/counter');
const { createNotification } = require('./notificationService');
const fileParsingService = require('./fileParsingService');

let intervalId = null;
let isProcessing = false;

const path = require('path');
const yauzl = require('yauzl');

function getMimeType(filename) {
  const ext = filename.split('.').pop().toLowerCase();
  const mimeMap = {
    'pdf': 'application/pdf',
    'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xls': 'application/vnd.ms-excel',
    'csv': 'text/csv',
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'dwg': 'image/vnd.dwg',
    'dxf': 'image/vnd.dxf',
    'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'txt': 'text/plain'
  };
  return mimeMap[ext] || 'application/octet-stream';
}

function unzipBuffer(buffer) {
  return new Promise((resolve, reject) => {
    const files = [];
    yauzl.fromBuffer(buffer, { lazyEntries: true }, (err, zipfile) => {
      if (err) return reject(err);

      zipfile.readEntry();
      zipfile.on('entry', (entry) => {
        if (/\/$/.test(entry.fileName)) {
          zipfile.readEntry();
        } else {
          zipfile.openReadStream(entry, (err, readStream) => {
            if (err) return reject(err);
            const chunks = [];
            readStream.on('data', (chunk) => chunks.push(chunk));
            readStream.on('end', () => {
              const fileContent = Buffer.concat(chunks);
              const filename = path.basename(entry.fileName);
              files.push({
                filename,
                content: fileContent,
                contentType: getMimeType(filename),
                size: fileContent.length
              });
              zipfile.readEntry();
            });
          });
        }
      });

      zipfile.on('end', () => {
        resolve(files);
      });
      zipfile.on('error', (err) => {
        reject(err);
      });
    });
  });
}

/**
 * Helper to extract email address from raw "From" string format.
 */
function extractEmail(str) {
  const match = str.match(/<([^>]+)>/) || str.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/);
  return match ? match[1].trim() : str.trim();
}

/**
 * Strip quoted/forwarded content from an email body.
 */
function stripQuotedText(text) {
  if (!text) return '';
  const lines = text.split('\n');
  const cleanLines = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (
      /^>/.test(trimmed) ||
      /^-{3,}\s*(Original Message|Forwarded Message)/i.test(trimmed) ||
      /^On .+wrote:/i.test(trimmed) ||
      /^_{5,}/.test(trimmed)
    ) {
      break;
    }
    cleanLines.push(line);
  }
  return cleanLines.join('\n').trim();
}

/**
 * Detects if an email is a bounce, auto-response, or system notification.
 */
function isAutoGeneratedOrSpam(parsed) {
  const fromText = parsed.from?.text || '';
  const senderEmail = (parsed.from?.value?.[0]?.address || extractEmail(fromText) || '').toLowerCase();
  const subject = (parsed.subject || '').toLowerCase();

  const imapUser = (process.env.IMAP_USER || 'ai@petrovalves.co.in').toLowerCase();
  const smtpUser = (process.env.SMTP_USER || 'ai@petrovalves.co.in').toLowerCase();
  if (senderEmail && (senderEmail === imapUser || senderEmail === smtpUser)) {
    return { isSpam: true, reason: `Sender is the bot's own address (${senderEmail})` };
  }

  const blacklistEmailPatterns = [
    'noreply', 'no-reply', 'donotreply', 'no_reply',
    'mailer-daemon', 'mailer_daemon', 'postmaster', 'mail-daemon',
    'newsletter', 'alert', 'notification', 'bounce', 'autoresponse'
  ];

  if (blacklistEmailPatterns.some(pattern => senderEmail.includes(pattern))) {
    return { isSpam: true, reason: `Sender address contains blacklisted keyword "${senderEmail}"` };
  }

  if (parsed.headers) {
    const autoSubmitted = parsed.headers.get('auto-submitted');
    if (autoSubmitted) {
      const val = String(autoSubmitted).toLowerCase();
      if (val && val !== 'no') {
        return { isSpam: true, reason: `Auto-Submitted header is "${val}"` };
      }
    }
    const precedence = parsed.headers.get('precedence');
    if (precedence) {
      const val = String(precedence).toLowerCase();
      if (['bulk', 'junk', 'list'].includes(val)) {
        return { isSpam: true, reason: `Precedence header is "${val}"` };
      }
    }
  }

  return { isSpam: false };
}

/**
 * Sends a unified acknowledgement email listing all created or matched enquiries back to the customer.
 */
async function sendAutomatedRepliesUnified(recipientEmail, contactName, enquiriesData, incomingEmailMsg = null) {
  const senderEmail = process.env.EMAIL_USER || 'ai@petrovalves.co.in';

  let itemsHtml = '';
  let itemsText = '';

  enquiriesData.forEach((item, idx) => {
    let statusBadgeColor = '#2563eb'; // Blue for New
    if (item.status === 'Needs Review') statusBadgeColor = '#d97706'; // Yellow/Orange
    else if (item.status === 'Verified') statusBadgeColor = '#0d9488'; // Teal
    else if (item.status === 'Ready for Offer') statusBadgeColor = '#059669'; // Green

    const missingSection = item.missingFields && item.missingFields.length > 0
      ? `<div style="margin-top:8px;padding:8px 12px;background-color:#fffbeb;border:1px solid #fef3c7;border-radius:8px;color:#b45309;font-size:12px;">
          <strong>Pending Details:</strong> Please reply to this email with: ${item.missingFields.map(f => f.fieldLabel).join(', ')}
         </div>`
      : `<div style="margin-top:8px;padding:8px 12px;background-color:#f0fdf4;border:1px solid #dcfce7;border-radius:8px;color:#15803d;font-size:12px;">
          <strong>Status:</strong> Specifications complete. Ready for offer generation.
         </div>`;

    itemsHtml += `
      <div style="border-bottom:1px solid #e2e8f0;padding:15px 0;margin-bottom:10px;">
        <div style="display:flex;justify-content:space-between;align-items:center;">
          <span style="font-size:14px;font-weight:bold;color:#1e293b;">Item #${idx + 1}: ${item.productDescription}</span>
          <span style="background-color:${statusBadgeColor};color:#ffffff;font-size:11px;font-weight:bold;padding:2px 8px;border-radius:20px;text-transform:uppercase;">${item.status}</span>
        </div>
        <div style="font-size:12px;color:#64748b;margin-top:4px;">
          Ref ID: <strong style="color:#2563eb;">${item.enquiryId}</strong> | Qty: ${item.quantity} ${item.unit || 'NOS'} | Category: ${item.productCategory}
        </div>
        ${missingSection}
      </div>
    `;

    itemsText += `Item #${idx + 1}: ${item.productDescription}\nRef ID: ${item.enquiryId} | Status: ${item.status}\n`;
    if (item.missingFields && item.missingFields.length > 0) {
      itemsText += `Pending Details: ${item.missingFields.map(f => f.fieldLabel).join(', ')}\n`;
    } else {
      itemsText += `Status: Specifications complete.\n`;
    }
    itemsText += `\n`;
  });

  const refsSubject = enquiriesData.map(e => e.enquiryId).join(', ');
  const defaultSubject = `Acknowledgement: Enquiries Registered [Ref: ${refsSubject}]`;
  let subject = defaultSubject;

  // Threading: If we have an incoming email subject containing ENQ-, preserve that subject (ensuring it has Re:)
  if (incomingEmailMsg && incomingEmailMsg.subject) {
    const originalSubject = incomingEmailMsg.subject.trim();
    if (originalSubject.toUpperCase().includes('ENQ-')) {
      if (/^(re|fwd|fw)\s*:/i.test(originalSubject)) {
        subject = originalSubject;
      } else {
        subject = `Re: ${originalSubject}`;
      }
    }
  }

  const textContent = `Dear ${contactName},

Thank you for your enquiry. We have successfully registered/updated your requests in our system:

${itemsText}
Our sales team is preparing your commercial quotation and will get in touch shortly.

Best regards,
Petro Valve AI Team
${senderEmail}`;

  const htmlContent = `
    <div style="font-family:'Helvetica Neue',Arial,sans-serif;padding:25px;color:#334155;line-height:1.6;max-width:650px;border:1px solid #e2e8f0;border-radius:16px;">
      <div style="border-bottom:2px solid #2563eb;padding-bottom:15px;margin-bottom:20px;">
        <h2 style="color:#1e3a8a;margin:0;font-size:20px;">Petro Valve AI Assistant</h2>
        <span style="font-size:11px;font-weight:bold;color:#64748b;text-transform:uppercase;letter-spacing:0.05em;">Multi-Enquiry Registration Summary</span>
      </div>
      <p>Dear <strong>${contactName}</strong>,</p>
      <p>Thank you for reaching out to Petro Valve. We have registered/updated your requests under the following Reference IDs:</p>
      
      <div style="background-color:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;padding:15px;margin:20px 0;">
        <h4 style="margin-top:0;color:#475569;font-size:13px;text-transform:uppercase;letter-spacing:0.05em;margin-bottom:10px;">Enquiries Status Summary:</h4>
        ${itemsHtml}
      </div>

      <p>Our sales team is preparing your commercial quotation and will get in touch with you shortly.</p>
      <p style="margin-top:30px;font-size:12px;color:#94a3b8;">
        Best regards,<br/>
        <strong>Petro Valve Sales Team</strong><br/>
        <a href="mailto:${senderEmail}" style="color:#2563eb;text-decoration:none;">${senderEmail}</a>
      </p>
    </div>`;

  // Build headers for thread grouping
  const mailHeaders = {};
  if (incomingEmailMsg && incomingEmailMsg.messageId) {
    mailHeaders['In-Reply-To'] = incomingEmailMsg.messageId;
    mailHeaders['References'] = incomingEmailMsg.messageId;
  }

  // 1. Try SMTP first
  try {
    const port = parseInt(process.env.SMTP_PORT || 465, 10);
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'mail.petrovalves.co.in',
      port: port,
      secure: port === 465,
      auth: {
        user: process.env.SMTP_USER || 'ai@petrovalves.co.in',
        pass: process.env.SMTP_PASS || 'Ai@@27042026'
      },
      connectionTimeout: 5000,
      greetingTimeout: 5000
    });

    const mailOptions = {
      from: `"Petro Valve AI Assistant" <${senderEmail}>`,
      to: recipientEmail,
      subject: subject,
      text: textContent,
      html: htmlContent
    };

    if (Object.keys(mailHeaders).length > 0) {
      mailOptions.headers = mailHeaders;
    }

    const info = await transporter.sendMail(mailOptions);

    console.log(`[Email Bot] Unified reply sent via SMTP to ${recipientEmail}. MessageId: ${info.messageId}`);
    return;
  } catch (smtpErr) {
    console.error(`[Email Bot] SMTP send failed: ${smtpErr.message}. Trying fallback to Brevo HTTP API...`);
    if (process.env.BREVO_API_KEY) {
      try {
        const { sendEmailViaBrevoApi } = require('./emailService');
        const brevoOptions = {
          to: recipientEmail,
          subject: subject,
          text: textContent,
          html: htmlContent
        };

        if (Object.keys(mailHeaders).length > 0) {
          brevoOptions.headers = mailHeaders;
        }

        await sendEmailViaBrevoApi(brevoOptions);
        console.log(`[Email Bot] Unified reply successfully sent via Brevo HTTP API to ${recipientEmail}`);
      } catch (fallbackErr) {
        console.error(`[Email Bot] Brevo HTTP API fallback also failed: ${fallbackErr.message}`);
      }
    } else {
      console.error(`[Email Bot] No BREVO_API_KEY set. Cannot try fallback.`);
    }
  }
}

/**
 * Handles the creation of Customer, Enquiry, Task and Notification from a single email.
 */
async function processEmailMessage(parsed) {
  const fromText = parsed.from?.text || '';
  const senderEmail = (parsed.from?.value?.[0]?.address || extractEmail(fromText)).toLowerCase();
  const senderName = parsed.from?.value?.[0]?.name || fromText.split('<')[0].replace(/"/g, '').trim() || 'Email Sender';
  const subject = parsed.subject || 'No Subject';
  const bodyText = parsed.text || parsed.html?.replace(/<[^>]+>/g, '') || '';
  const htmlBody = parsed.html || '';
  const messageId = parsed.messageId || '';

  // 1. Duplicate Check
  const contentRaw = `${senderEmail}|${subject}|${bodyText}`;
  const contentHash = crypto.createHash('sha256').update(contentRaw).digest('hex');

  let existingProcessed = null;
  if (messageId) {
    existingProcessed = await ProcessedEmail.findOne({ messageId });
  } else {
    existingProcessed = await ProcessedEmail.findOne({ contentHash });
  }

  if (existingProcessed) {
    console.log(`[Email Bot] Duplicate email detected (Message-ID: ${messageId || 'N/A'}, Hash: ${contentHash}). Skipping.`);
    return;
  }

  // Save ProcessedEmail record
  await ProcessedEmail.create({
    messageId: messageId || undefined,
    contentHash,
    sender: senderEmail,
    subject
  });

  // Log Ingestion Rate Metric
  const Metrics = require('../models/Metrics');
  await Metrics.create({
    metricName: 'EmailIngestionRate',
    value: 1,
    metadata: { sender: senderEmail, subject }
  }).catch(err => console.error('[Email Bot] Failed to log email ingestion metric:', err.message));

  // Find or create Customer
  let customer = await Customer.findOne({
    $or: [
      { emailAddress: senderEmail.toLowerCase() },
      { alternateEmail: senderEmail.toLowerCase() }
    ]
  });

  if (!customer) {
    console.log(`[Email Bot] Customer not found. Auto-creating customer for ${senderEmail}`);
    customer = await Customer.create({
      companyName: 'Individual Customer',
      primaryContactName: senderName,
      mobileNumber: '0000000000',
      emailAddress: senderEmail.toLowerCase(),
      customerId: `CUS-${Date.now().toString().slice(-6)}`,
      sourceChannel: 'Email'
    });
  }

  // 2. Thread Matching Priority Logic to get the threadId
  let matchedEnquiries = [];
  const parentMessageIds = [];
  if (parsed.inReplyTo) parentMessageIds.push(parsed.inReplyTo);
  if (parsed.references) {
    if (Array.isArray(parsed.references)) parentMessageIds.push(...parsed.references);
    else parentMessageIds.push(parsed.references);
  }

  // A. Reference IDs in subject/body
  const refMatch = (subject + ' ' + bodyText).match(/ENQ-\d{4}-\d{2}-\d{4}/gi);
  if (refMatch) {
    const matchedIds = [...new Set(refMatch.map(id => id.toUpperCase()))];
    matchedEnquiries = await Enquiry.find({ enquiryId: { $in: matchedIds } }).populate('customer');
  }

  // B. Fallback to thread headers
  if (matchedEnquiries.length === 0 && parentMessageIds.length > 0) {
    const parentMsg = await EmailMessage.findOne({ messageId: { $in: parentMessageIds } });
    if (parentMsg && parentMsg.threadId) {
      matchedEnquiries = await Enquiry.find({ threadId: parentMsg.threadId }).populate('customer');
    }
  }

  // C. Fallback to sender email
  if (matchedEnquiries.length === 0) {
    const isReplySubject = /^(re|fwd|fw)\s*:/i.test(subject.trim());
    if (isReplySubject) {
      const activeEnquiries = await Enquiry.find({
        customer: customer._id,
        status: { $in: ['New', 'Contacted', 'Technical Review', 'Needs Review', 'Verified'] }
      }).populate('customer');

      if (activeEnquiries.length === 1) {
        matchedEnquiries = [activeEnquiries[0]];
      }
    }
  }

  const threadId = matchedEnquiries.length > 0 ? matchedEnquiries[0].threadId : crypto.randomBytes(16).toString('hex');

  // 3. Save incoming attachments immediately
  const savedAttachments = [];
  if (parsed.attachments && parsed.attachments.length > 0) {
    const { uploadFile } = require('./localStorageService');
    for (const att of parsed.attachments) {
      try {
        const storagePath = await uploadFile(att.content, att.filename, att.contentType);

        const parentAttachment = await Attachment.create({
          customerId: customer._id,
          threadId,
          originalMessageId: messageId,
          originalFileName: att.filename,
          fileType: att.contentType,
          fileSize: att.size,
          storagePath,
          extractedText: '',
          extractionStatus: 'PENDING',
          processingStatus: 'Pending'
        });
        savedAttachments.push(parentAttachment);

        // Check if attachment is a ZIP file and extract inner files
        const ext = att.filename.split('.').pop().toLowerCase();
        if (ext === 'zip' || att.contentType === 'application/zip' || att.contentType === 'application/x-zip-compressed') {
          console.log(`[Email Bot] Extracting zip file attachment: ${att.filename}`);
          try {
            const extractedFiles = await unzipBuffer(att.content);
            console.log(`[Email Bot] Zip ${att.filename} extracted. Found ${extractedFiles.length} file(s).`);
            for (const ef of extractedFiles) {
              const efStoragePath = await uploadFile(ef.content, ef.filename, ef.contentType);
              const efAttachment = await Attachment.create({
                customerId: customer._id,
                threadId,
                originalMessageId: messageId,
                originalFileName: ef.filename,
                fileType: ef.contentType,
                fileSize: ef.size,
                storagePath: efStoragePath,
                extractedText: '',
                extractionStatus: 'PENDING',
                processingStatus: 'Pending'
              });
              savedAttachments.push(efAttachment);
            }
          } catch (zipErr) {
            console.error(`[Email Bot] Error extracting zip attachment ${att.filename}:`, zipErr.message);
          }
        }
      } catch (err) {
        console.error(`[Email Bot] Failed to save raw attachment ${att.filename}:`, err.message);
      }
    }
  }

  // 4. Archive Email Message
  const emailMsg = await EmailMessage.create({
    messageId: messageId || undefined,
    threadId,
    sender: senderEmail,
    recipients: parsed.to ? (Array.isArray(parsed.to.value) ? parsed.to.value.map(v => v.address) : [parsed.to.text]) : [],
    cc: parsed.cc ? (Array.isArray(parsed.cc.value) ? parsed.cc.value.map(v => v.address) : [parsed.cc.text]) : [],
    bcc: parsed.bcc ? (Array.isArray(parsed.bcc.value) ? parsed.bcc.value.map(v => v.address) : [parsed.bcc.text]) : [],
    subject,
    bodyText,
    htmlBody,
    attachments: savedAttachments.map(a => a._id),
    receivedAt: parsed.date || new Date(),
    processedAt: new Date(),
    processingStatus: 'Pending',
    processingMessage: 'Enqueued for background parsing'
  });

  // 5. Queue on EmailProcessingQueue
  const { emailProcessingQueue } = require('./queueHandlers');
  await emailProcessingQueue.add({ emailMessageId: emailMsg._id });
  console.log(`[Email Bot] Enqueued EmailMessage ${emailMsg._id} to EmailProcessingQueue`);
}

/**
 * Checks the inbox for unseen emails, parses them, and runs extraction/replies.
 */
async function checkEmails() {
  if (isProcessing) {
    console.log('[Email Bot] Previous execution is still processing. Skipping...');
    return;
  }
  isProcessing = true;

  const imapHost = process.env.IMAP_HOST;
  const imapPort = parseInt(process.env.IMAP_PORT || 993, 10);
  const imapUser = process.env.IMAP_USER;
  const imapPass = process.env.IMAP_PASS;

  if (!imapHost || !imapUser || !imapPass) {
    console.warn('[Email Bot] IMAP credentials or host missing in environment variables. Email bot polling skipped.');
    isProcessing = false;
    return;
  }

  const client = new ImapFlow({
    host: imapHost,
    port: imapPort,
    secure: true,
    auth: {
      user: imapUser,
      pass: imapPass
    },
    logger: false,
    connectionTimeout: 10000,
    greetingTimeout: 10000
  });

  try {
    console.log(`[Email Bot] Connecting to IMAP mailbox: ${imapHost}:${imapPort} as ${imapUser}...`);
    await client.connect();

    let lock = await client.getMailboxLock('INBOX');
    try {
      const uids = await client.search({ seen: false }, { uid: true });
      console.log(`[Email Bot] Found ${uids.length} unseen email(s) in INBOX.`);

      for (const uid of uids) {
        console.log(`[Email Bot] Fetching raw message source for UID ${uid}...`);
        try {
          const emailStream = await client.download(uid, null, { uid: true });
          const parsed = await simpleParser(emailStream.content);

          const spamCheck = isAutoGeneratedOrSpam(parsed);
          if (spamCheck.isSpam) {
            console.log(`[Email Bot] Skipping UID ${uid}: ${spamCheck.reason}`);
            await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
            continue;
          }

          parsed.uid = uid; // Attach UID for traceability
          await processEmailMessage(parsed);
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          console.log(`[Email Bot] Successfully processed and marked UID ${uid} as SEEN.`);
        } catch (msgErr) {
          console.error(`[Email Bot] Failed to process message UID ${uid}:`, msgErr);
        }
      }
    } finally {
      lock.release();
    }

    await client.logout();
    console.log('[Email Bot] Logged out from IMAP box successfully.');
  } catch (err) {
    console.error('[Email Bot] Connection/processing failed:', err.message);
  } finally {
    isProcessing = false;
  }
}

/**
 * Starts the background polling worker.
 */
exports.start = () => {
  if (intervalId) {
    console.log('[Email Bot] Worker already running.');
    return;
  }

  console.log('[Email Bot] Starting background AI email processing service (1-minute polling interval)...');
  checkEmails();
  intervalId = setInterval(checkEmails, 10000);
};

/**
 * Stops the background worker.
 */
exports.stop = () => {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
    console.log('[Email Bot] Background worker stopped.');
  }
};

exports.processEmailMessage = processEmailMessage;
exports.checkEmails = checkEmails;
exports.sendAutomatedRepliesUnified = sendAutomatedRepliesUnified;
exports.stripQuotedText = stripQuotedText;
