const { ImapFlow } = require('imapflow');
const { simpleParser } = require('mailparser');
const nodemailer = require('nodemailer');
const crypto = require('crypto');
const aiService = require('./aiService');
const Customer = require('../models/Customer');
const Enquiry = require('../models/Enquiry');
const User = require('../models/User');
const Task = require('../models/Task');
const FollowUp = require('../models/FollowUp');
const EmailMessage = require('../models/EmailMessage');
const ProcessedEmail = require('../models/ProcessedEmail');
const Attachment = require('../models/Attachment');
const FieldDefinition = require('../models/FieldDefinition');
const { getNextSequenceValue } = require('../utils/counter');
const { createNotification } = require('./notificationService');
const fileParsingService = require('./fileParsingService');

let intervalId = null;
let isProcessing = false;

const path = require('path');
const yauzl = require('yauzl');

function getMimeType(filename) {
  const ext = filename.split('.').pop().toLowerCase();
  const mimeMap = {
    'pdf': 'application/pdf',
    'xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xls': 'application/vnd.ms-excel',
    'csv': 'text/csv',
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'dwg': 'image/vnd.dwg',
    'dxf': 'image/vnd.dxf',
    'docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'txt': 'text/plain'
  };
  return mimeMap[ext] || 'application/octet-stream';
}

function unzipBuffer(buffer) {
  return new Promise((resolve, reject) => {
    const files = [];
    yauzl.fromBuffer(buffer, { lazyEntries: true }, (err, zipfile) => {
      if (err) return reject(err);

      zipfile.readEntry();
      zipfile.on('entry', (entry) => {
        if (/\/$/.test(entry.fileName)) {
          zipfile.readEntry();
        } else {
          zipfile.openReadStream(entry, (err, readStream) => {
            if (err) return reject(err);
            const chunks = [];
            readStream.on('data', (chunk) => chunks.push(chunk));
            readStream.on('end', () => {
              const fileContent = Buffer.concat(chunks);
              const filename = path.basename(entry.fileName);
              files.push({
                filename,
                content: fileContent,
                contentType: getMimeType(filename),
                size: fileContent.length
              });
              zipfile.readEntry();
            });
          });
        }
      });

      zipfile.on('end', () => {
        resolve(files);
      });
      zipfile.on('error', (err) => {
        reject(err);
      });
    });
  });
}

/**
 * Helper to extract email address from raw "From" string format.
 */
function extractEmail(str) {
  const match = str.match(/<([^>]+)>/) || str.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/);
  return match ? match[1].trim() : str.trim();
}

/**
 * Strip quoted/forwarded content from an email body.
 */
function stripQuotedText(text) {
  if (!text) return '';
  const lines = text.split('\n');
  const cleanLines = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (
      /^>/.test(trimmed) ||
      /^-{3,}\s*(Original Message|Forwarded Message)/i.test(trimmed) ||
      /^-{5,}\s*Forwarded message\s*-{5,}/i.test(trimmed) ||
      /^On .+wrote:\s*$/i.test(trimmed) ||
      /^On\s+\d{1,2}\s+\w+\s+\d{4}.+wrote:\s*$/i.test(trimmed) ||
      /^_{5,}/.test(trimmed) ||
      /^From:\s*.+\s*$/i.test(trimmed) && /Sent:|Date:/i.test(lines[lines.indexOf(line) + 1] || '') ||
      /^Begin forwarded message:/i.test(trimmed) ||
      /^\*From:\*/i.test(trimmed) ||
      /^Sent from my (iPhone|iPad|Galaxy|Android)/i.test(trimmed)
    ) {
      break;
    }
    cleanLines.push(line);
  }
  return cleanLines.join('\n').trim();
}

/**
 * Detects if an email is a bounce, auto-response, or system notification.
 */
function isAutoGeneratedOrSpam(parsed) {
  const fromText = parsed.from?.text || '';
  const senderEmail = (parsed.from?.value?.[0]?.address || extractEmail(fromText) || '').toLowerCase();
  const subject = (parsed.subject || '').toLowerCase();

  const imapUser = (process.env.IMAP_USER || 'ai@petrovalves.co.in').toLowerCase();
  const smtpUser = (process.env.SMTP_USER || 'ai@petrovalves.co.in').toLowerCase();
  if (senderEmail && (senderEmail === imapUser || senderEmail === smtpUser)) {
    return { isSpam: true, reason: `Sender is the bot's own address (${senderEmail})` };
  }

  const blacklistEmailPatterns = [
    'noreply', 'no-reply', 'donotreply', 'no_reply',
    'mailer-daemon', 'mailer_daemon', 'postmaster', 'mail-daemon',
    'newsletter', 'alert', 'notification', 'bounce', 'autoresponse'
  ];

  if (blacklistEmailPatterns.some(pattern => senderEmail.includes(pattern))) {
    return { isSpam: true, reason: `Sender address contains blacklisted keyword "${senderEmail}"` };
  }

  if (parsed.headers) {
    const autoSubmitted = parsed.headers.get('auto-submitted');
    if (autoSubmitted) {
      const val = String(autoSubmitted).toLowerCase();
      if (val && val !== 'no') {
        return { isSpam: true, reason: `Auto-Submitted header is "${val}"` };
      }
    }
    const precedence = parsed.headers.get('precedence');
    if (precedence) {
      const val = String(precedence).toLowerCase();
      if (['bulk', 'junk', 'list'].includes(val)) {
        return { isSpam: true, reason: `Precedence header is "${val}"` };
      }
    }
  }

  return { isSpam: false };
}

/**
 * Sends a unified acknowledgement email listing all created or matched enquiries back to the customer.
 */
async function sendAutomatedRepliesUnified(recipientEmail, contactName, enquiriesData, incomingEmailMsg = null, isReminder = false) {
  const senderEmail = process.env.EMAIL_USER || 'ai@petrovalves.co.in';

  // Determine targeted email account (info@, sales@, support@)
  let targetAccount = 'info@';
  if (incomingEmailMsg) {
    const toRecipients = incomingEmailMsg.recipients || [];
    const ccRecipients = incomingEmailMsg.cc || [];
    const allRecipients = [...toRecipients, ...ccRecipients].map(r => String(r).toLowerCase());

    if (allRecipients.some(r => r.includes('sales@'))) {
      targetAccount = 'sales@';
    } else if (allRecipients.some(r => r.includes('support@'))) {
      targetAccount = 'support@';
    }
  } else if (enquiriesData && enquiriesData.length > 0 && enquiriesData[0].emailAccount) {
    targetAccount = enquiriesData[0].emailAccount;
  }

  const accountKey = targetAccount.replace('@', ''); // 'info@' -> 'info'

  // Load configuration from SystemSettings
  const SystemSettings = require('../models/SystemSettings');
  const settings = await SystemSettings.findOne({ _singleton: 'global' });
  const config = settings?.emailAccountsConfig?.[accountKey] || {
    autoReply: true,
    subjectTemplate: 'Acknowledgement: Enquiries Registered [Ref: {refs}]',
    bodyTemplate: 'Dear {contactName},\n\nThank you for your enquiry. We have successfully registered/updated your requests in our system:\n\n{itemsText}\n\nOur sales team is preparing your commercial quotation and will get in touch shortly.\n\nBest regards,\nPetro Valve AI Team'
  };

  if (config.autoReply === false) {
    console.log(`[Email Bot] Auto-acknowledgement is disabled for email account ${targetAccount}. Skipping reply.`);
    return;
  }

  // Build a simple list of reference IDs for the subject line
  const refsSubject = enquiriesData.map(e => e.enquiryId).join(', ');

  // ── Subject ────────────────────────────────────────────────────────
  let subject = `Thank You for Your Enquiry [Ref: ${refsSubject}]`;

  // Threading: preserve the original subject if it already mentions an ENQ-
  if (incomingEmailMsg && incomingEmailMsg.subject) {
    const originalSubject = incomingEmailMsg.subject.trim();
    if (originalSubject.toUpperCase().includes('ENQ-')) {
      subject = /^(re|fwd|fw)\s*:/i.test(originalSubject)
        ? originalSubject
        : `Re: ${originalSubject}`;
    } else {
      subject = /^(re|fwd|fw)\s*:/i.test(originalSubject)
        ? originalSubject
        : `Re: ${originalSubject}`;
    }
  }

  // ── Plain-text body ────────────────────────────────────────────────
  const textContent = `Dear ${contactName},

Thank you for reaching out to Petro Valves Pvt. Ltd.

We have successfully received your enquiry${enquiriesData.length > 1 ? ' comprising ' + enquiriesData.length + ' items' : ''} and it has been registered in our system under reference${enquiriesData.length > 1 ? 's' : ''}: ${refsSubject}.

Our technical and commercial team is currently reviewing your requirements. A detailed quotation will be shared with you at the earliest.

Should you have any additional specifications, drawings, or documents to share, please feel free to reply to this email.

We appreciate your interest and look forward to working with you.

Warm regards,
Petro Valves Pvt. Ltd.
Sales & Technical Team
Email: ${process.env.EMAIL_USER || 'ai@petrovalves.co.in'}
`;

  // ── HTML body ──────────────────────────────────────────────────────
  const htmlContent = `
    <div style="font-family:'Segoe UI','Helvetica Neue',Arial,sans-serif;max-width:620px;margin:0 auto;color:#334155;line-height:1.7;">
      <!-- Header -->
      <div style="background:linear-gradient(135deg,#1e3a8a 0%,#2563eb 100%);padding:24px 28px;border-radius:12px 12px 0 0;">
        <h2 style="margin:0;color:#ffffff;font-size:20px;font-weight:700;letter-spacing:-0.3px;">Petro Valves Pvt. Ltd.</h2>
        <p style="margin:4px 0 0;color:#93c5fd;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;">Enquiry Acknowledgement</p>
      </div>

      <!-- Body -->
      <div style="background:#ffffff;border:1px solid #e2e8f0;border-top:none;padding:28px;border-radius:0 0 12px 12px;">
        <p style="font-size:15px;margin-top:0;">Dear <strong>${contactName}</strong>,</p>

        <p style="font-size:14px;">Thank you for reaching out to us. We have successfully received your enquiry and it has been registered in our system.</p>

        <!-- Reference IDs -->
        <div style="background:#f0f9ff;border:1px solid #bae6fd;border-radius:8px;padding:14px 18px;margin:20px 0;">
          <p style="margin:0 0 6px;font-size:12px;font-weight:700;color:#0369a1;text-transform:uppercase;letter-spacing:0.04em;">Your Reference${enquiriesData.length > 1 ? 's' : ''}</p>
          <p style="margin:0;font-size:15px;font-weight:700;color:#0c4a6e;letter-spacing:0.02em;">${refsSubject}</p>
        </div>

        <p style="font-size:14px;">Our technical and commercial team is currently reviewing your requirements. A detailed quotation will be shared with you at the earliest.</p>

        <p style="font-size:14px;">Should you have any additional specifications, drawings, or documents to share, please feel free to reply directly to this email.</p>

        <p style="font-size:14px;margin-bottom:0;">We appreciate your interest and look forward to working with you.</p>

        <!-- Signature -->
        <div style="margin-top:28px;padding-top:18px;border-top:1px solid #e2e8f0;">
          <p style="margin:0;font-size:14px;font-weight:600;color:#1e293b;">Warm regards,</p>
          <p style="margin:4px 0 0;font-size:14px;font-weight:700;color:#1e3a8a;">Petro Valves Pvt. Ltd.</p>
          <p style="margin:2px 0 0;font-size:12px;color:#64748b;">Sales & Technical Team</p>
          <p style="margin:2px 0 0;font-size:12px;">
            <a href="mailto:${process.env.EMAIL_USER || 'ai@petrovalves.co.in'}" style="color:#2563eb;text-decoration:none;">${process.env.EMAIL_USER || 'ai@petrovalves.co.in'}</a>
          </p>
        </div>
      </div>
    </div>`;

  // ── Thread headers ─────────────────────────────────────────────────
  const mailHeaders = {};
  if (incomingEmailMsg && incomingEmailMsg.messageId) {
    mailHeaders['In-Reply-To'] = incomingEmailMsg.messageId;
    const prevRefs = incomingEmailMsg.references || '';
    const refParts = prevRefs
      ? [...prevRefs.split(/\s+/).filter(Boolean), incomingEmailMsg.messageId]
      : [incomingEmailMsg.messageId];
    mailHeaders['References'] = [...new Set(refParts)].join(' ');
  }

  // ── Send via SMTP (primary) ────────────────────────────────────────
  try {
    const port = parseInt(process.env.SMTP_PORT || 465, 10);
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'mail.petrovalves.co.in',
      port: port,
      secure: port === 465,
      auth: {
        user: process.env.SMTP_USER || 'ai@petrovalves.co.in',
        pass: process.env.SMTP_PASS || 'Ai@@27042026'
      },
      connectionTimeout: 5000,
      greetingTimeout: 5000
    });

    const mailOptions = {
      from: `"Petro Valves Pvt. Ltd." <${senderEmail}>`,
      to: recipientEmail,
      subject: subject,
      text: textContent,
      html: htmlContent
    };

    if (Object.keys(mailHeaders).length > 0) {
      mailOptions.headers = mailHeaders;
    }

    const info = await transporter.sendMail(mailOptions);
    console.log(`[Email Bot] Acknowledgement reply sent via SMTP to ${recipientEmail}. MessageId: ${info.messageId}`);
    return;
  } catch (smtpErr) {
    console.error(`[Email Bot] SMTP send failed: ${smtpErr.message}. Trying fallback to Brevo HTTP API...`);
    if (process.env.BREVO_API_KEY) {
      try {
        const { sendEmailViaBrevoApi } = require('./emailService');
        const brevoOptions = {
          to: recipientEmail,
          subject: subject,
          text: textContent,
          html: htmlContent
        };
        if (Object.keys(mailHeaders).length > 0) {
          brevoOptions.headers = mailHeaders;
        }
        await sendEmailViaBrevoApi(brevoOptions);
        console.log(`[Email Bot] Acknowledgement reply sent via Brevo HTTP API to ${recipientEmail}`);
      } catch (fallbackErr) {
        console.error(`[Email Bot] Brevo HTTP API fallback also failed: ${fallbackErr.message}`);
      }
    } else {
      console.error(`[Email Bot] No BREVO_API_KEY set. Cannot try fallback.`);
    }
  }
}

/**
 * Handles the creation of Customer, Enquiry, Task and Notification from a single email.
 */
async function processEmailMessage(parsed) {
  const fromText = parsed.from?.text || '';
  const senderEmail = (parsed.from?.value?.[0]?.address || extractEmail(fromText)).toLowerCase();
  const senderName = parsed.from?.value?.[0]?.name || fromText.split('<')[0].replace(/"/g, '').trim() || 'Email Sender';
  const subject = parsed.subject || 'No Subject';
  const bodyText = parsed.text || parsed.html?.replace(/<[^>]+>/g, '') || '';
  const htmlBody = parsed.html || '';
  const messageId = parsed.messageId || '';

  // 1. Duplicate Check
  const contentRaw = `${senderEmail}|${subject}|${bodyText}`;
  const contentHash = crypto.createHash('sha256').update(contentRaw).digest('hex');

  let existingProcessed = null;
  if (messageId) {
    existingProcessed = await ProcessedEmail.findOne({ messageId });
  } else {
    existingProcessed = await ProcessedEmail.findOne({ contentHash });
  }

  if (existingProcessed) {
    console.log(`[Email Bot] Duplicate email detected (Message-ID: ${messageId || 'N/A'}, Hash: ${contentHash}). Skipping.`);
    return;
  }

  // Save ProcessedEmail record
  await ProcessedEmail.create({
    messageId: messageId || undefined,
    contentHash,
    sender: senderEmail,
    subject
  });

  // Log Ingestion Rate Metric
  const Metrics = require('../models/Metrics');
  await Metrics.create({
    metricName: 'EmailIngestionRate',
    value: 1,
    metadata: { sender: senderEmail, subject }
  }).catch(err => console.error('[Email Bot] Failed to log email ingestion metric:', err.message));

  // Find or create Customer
  let customer = await Customer.findOne({
    $or: [
      { emailAddress: senderEmail.toLowerCase() },
      { alternateEmail: senderEmail.toLowerCase() }
    ]
  });

  if (!customer) {
    console.log(`[Email Bot] Customer not found. Auto-creating customer for ${senderEmail}`);
    customer = await Customer.create({
      companyName: 'Individual Customer',
      primaryContactName: senderName,
      mobileNumber: '0000000000',
      emailAddress: senderEmail.toLowerCase(),
      customerId: `CUS-${Date.now().toString().slice(-6)}`,
      sourceChannel: 'Email'
    });
  }

  // 2. Thread Matching Priority Logic to get the threadId
  let matchedEnquiries = [];
  const parentMessageIds = [];
  if (parsed.inReplyTo) parentMessageIds.push(parsed.inReplyTo);
  if (parsed.references) {
    if (Array.isArray(parsed.references)) parentMessageIds.push(...parsed.references);
    else parentMessageIds.push(parsed.references);
  }

  // A. Reference IDs in subject/body
  const refMatch = (subject + ' ' + bodyText).match(/ENQ-\d{4}-\d{2}-\d{4}/gi);
  if (refMatch) {
    const matchedIds = [...new Set(refMatch.map(id => id.toUpperCase()))];
    matchedEnquiries = await Enquiry.find({ enquiryId: { $in: matchedIds } }).populate('customer');
  }

  // B. Fallback to thread headers
  if (matchedEnquiries.length === 0 && parentMessageIds.length > 0) {
    const parentMsg = await EmailMessage.findOne({ messageId: { $in: parentMessageIds } });
    if (parentMsg && parentMsg.threadId) {
      matchedEnquiries = await Enquiry.find({ threadId: parentMsg.threadId }).populate('customer');
    }
  }

  // C. Fallback to sender email
  if (matchedEnquiries.length === 0) {
    const isReplySubject = /^(re|fwd|fw)\s*:/i.test(subject.trim());
    if (isReplySubject) {
      const activeEnquiries = await Enquiry.find({
        customer: customer._id,
        status: { $in: ['New', 'Confirmed', 'Contacted', 'Technical Review', 'Needs Review', 'Verified'] }
      }).populate('customer');

      if (activeEnquiries.length === 1) {
        matchedEnquiries = [activeEnquiries[0]];
      }
    }
  }

  const threadId = matchedEnquiries.length > 0 ? matchedEnquiries[0].threadId : crypto.randomBytes(16).toString('hex');

  // 3. Save incoming attachments immediately
  const savedAttachments = [];
  if (parsed.attachments && parsed.attachments.length > 0) {
    const { uploadFile } = require('./localStorageService');
    for (const att of parsed.attachments) {
      try {
        const storagePath = await uploadFile(att.content, att.filename, att.contentType);

        const parentAttachment = await Attachment.create({
          customerId: customer._id,
          threadId,
          originalMessageId: messageId,
          originalFileName: att.filename,
          fileType: att.contentType,
          fileSize: att.size,
          storagePath,
          extractedText: '',
          extractionStatus: 'PENDING',
          processingStatus: 'Pending'
        });
        savedAttachments.push(parentAttachment);

        // Check if attachment is a ZIP file and extract inner files
        const ext = att.filename.split('.').pop().toLowerCase();
        if (ext === 'zip' || att.contentType === 'application/zip' || att.contentType === 'application/x-zip-compressed') {
          console.log(`[Email Bot] Extracting zip file attachment: ${att.filename}`);
          try {
            const extractedFiles = await unzipBuffer(att.content);
            console.log(`[Email Bot] Zip ${att.filename} extracted. Found ${extractedFiles.length} file(s).`);
            for (const ef of extractedFiles) {
              const efStoragePath = await uploadFile(ef.content, ef.filename, ef.contentType);
              const efAttachment = await Attachment.create({
                customerId: customer._id,
                threadId,
                originalMessageId: messageId,
                originalFileName: ef.filename,
                fileType: ef.contentType,
                fileSize: ef.size,
                storagePath: efStoragePath,
                extractedText: '',
                extractionStatus: 'PENDING',
                processingStatus: 'Pending'
              });
              savedAttachments.push(efAttachment);
            }
          } catch (zipErr) {
            console.error(`[Email Bot] Error extracting zip attachment ${att.filename}:`, zipErr.message);
          }
        }
      } catch (err) {
        console.error(`[Email Bot] Failed to save raw attachment ${att.filename}:`, err.message);
      }
    }
  }

  // 4. Archive Email Message (including threading headers)
  const parsedInReplyTo = parsed.inReplyTo || null;
  const parsedReferences = Array.isArray(parsed.references)
    ? parsed.references.join(' ')
    : (parsed.references || null);

  const emailMsg = await EmailMessage.create({
    messageId: messageId || undefined,
    threadId,
    sender: senderEmail,
    recipients: parsed.to ? (Array.isArray(parsed.to.value) ? parsed.to.value.map(v => v.address) : [parsed.to.text]) : [],
    cc: parsed.cc ? (Array.isArray(parsed.cc.value) ? parsed.cc.value.map(v => v.address) : [parsed.cc.text]) : [],
    bcc: parsed.bcc ? (Array.isArray(parsed.bcc.value) ? parsed.bcc.value.map(v => v.address) : [parsed.bcc.text]) : [],
    subject,
    bodyText,
    htmlBody,
    inReplyTo: parsedInReplyTo,
    references: parsedReferences,
    attachments: savedAttachments.map(a => a._id),
    receivedAt: parsed.date || new Date(),
    processedAt: new Date(),
    processingStatus: 'Pending',
    processingMessage: 'Enqueued for background parsing'
  });

  // 5. Queue on EmailProcessingQueue
  const { emailProcessingQueue } = require('./queueHandlers');
  await emailProcessingQueue.add({ emailMessageId: emailMsg._id });
  console.log(`[Email Bot] Enqueued EmailMessage ${emailMsg._id} to EmailProcessingQueue`);
}

/**
 * Checks the inbox for unseen emails, parses them, and runs extraction/replies.
 */
async function checkEmails() {
  if (isProcessing) {
    console.log('[Email Bot] Previous execution is still processing. Skipping...');
    return;
  }
  isProcessing = true;

  const imapHost = process.env.IMAP_HOST;
  const imapPort = parseInt(process.env.IMAP_PORT || 993, 10);
  const imapUser = process.env.IMAP_USER;
  const imapPass = process.env.IMAP_PASS;

  if (!imapHost || !imapUser || !imapPass) {
    console.warn('[Email Bot] IMAP credentials or host missing in environment variables. Email bot polling skipped.');
    isProcessing = false;
    return;
  }

  const client = new ImapFlow({
    host: imapHost,
    port: imapPort,
    secure: true,
    auth: {
      user: imapUser,
      pass: imapPass
    },
    logger: false,
    connectionTimeout: 30000,
    greetingTimeout: 30000
  });

  try {
    console.log(`[Email Bot] Connecting to IMAP mailbox: ${imapHost}:${imapPort} as ${imapUser}...`);
    await client.connect();

    let lock = await client.getMailboxLock('INBOX');
    try {
      const uids = await client.search({ seen: false }, { uid: true });
      console.log(`[Email Bot] Found ${uids.length} unseen email(s) in INBOX.`);

      for (const uid of uids) {
        console.log(`[Email Bot] Fetching raw message source for UID ${uid}...`);
        try {
          const emailStream = await client.download(uid, null, { uid: true });
          const parsed = await simpleParser(emailStream.content);

          const spamCheck = isAutoGeneratedOrSpam(parsed);
          if (spamCheck.isSpam) {
            console.log(`[Email Bot] Skipping UID ${uid}: ${spamCheck.reason}`);
            await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
            continue;
          }

          parsed.uid = uid; // Attach UID for traceability
          await processEmailMessage(parsed);
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          console.log(`[Email Bot] Successfully processed and marked UID ${uid} as SEEN.`);
        } catch (msgErr) {
          console.error(`[Email Bot] Failed to process message UID ${uid}:`, msgErr);
        }
      }
    } finally {
      lock.release();
    }

    await client.logout();
    console.log('[Email Bot] Logged out from IMAP box successfully.');
  } catch (err) {
    console.error('[Email Bot] Connection/processing failed:', err.message);
  } finally {
    isProcessing = false;
  }
}

/**
 * Starts the background polling worker.
 */
exports.start = () => {
  if (intervalId) {
    console.log('[Email Bot] Worker already running.');
    return;
  }

  console.log('[Email Bot] Starting background AI email processing service (1-minute polling interval)...');
  checkEmails();
  intervalId = setInterval(checkEmails, 10000);
};

/**
 * Stops the background worker.
 */
exports.stop = () => {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
    console.log('[Email Bot] Background worker stopped.');
  }
};

exports.processEmailMessage = processEmailMessage;
exports.checkEmails = checkEmails;
exports.sendAutomatedRepliesUnified = sendAutomatedRepliesUnified;
exports.stripQuotedText = stripQuotedText;
