const { ImapFlow } = require('imapflow');
const { simpleParser } = require('mailparser');
const nodemailer = require('nodemailer');
const aiService = require('./aiService');
const Customer = require('../models/Customer');
const Enquiry = require('../models/Enquiry');
const User = require('../models/User');
const Task = require('../models/Task');
const { getNextSequenceValue } = require('../utils/counter');
const { createNotification } = require('./notificationService');

let intervalId = null;
let isProcessing = false;

/**
 * Helper to extract email address from raw "From" string format:
 * "John Doe <john@example.com>" -> "john@example.com"
 */
function extractEmail(str) {
  const match = str.match(/<([^>]+)>/) || str.match(/([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z0-9._-]+)/);
  return match ? match[1].trim() : str.trim();
}

/**
 * Detects if an email is a bounce, auto-response, or system notification.
 */
function isAutoGeneratedOrSpam(parsed) {
  const fromText = parsed.from?.text || '';
  const senderEmail = (parsed.from?.value?.[0]?.address || extractEmail(fromText) || '').toLowerCase();
  const subject = (parsed.subject || '').toLowerCase();
  
  // Prevent infinite email feedback loop: check if sender is the bot's own email address
  const imapUser = (process.env.IMAP_USER || 'ai@petrovalvesco.in').toLowerCase();
  const smtpUser = (process.env.SMTP_USER || 'ai@petrovalvesco.in').toLowerCase();
  if (senderEmail && (senderEmail === imapUser || senderEmail === smtpUser)) {
    return { isSpam: true, reason: `Sender is the bot's own address (${senderEmail})` };
  }

  // 1. Check sender email blacklist pattern
  const blacklistEmailPatterns = [
    'noreply', 'no-reply', 'donotreply', 'no_reply',
    'mailer-daemon', 'mailer_daemon', 'postmaster', 'mail-daemon',
    'newsletter', 'alert', 'notification', 'bounce', 'autoresponse'
  ];
  
  if (blacklistEmailPatterns.some(pattern => senderEmail.includes(pattern))) {
    return { isSpam: true, reason: `Sender address contains blacklisted keyword "${senderEmail}"` };
  }

  // 2. Check subject pattern
  const blacklistSubjectPatterns = [
    'delivery status notification', 'undelivered mail', 'failure notice',
    'auto:', 'automatic reply', 'out of office', 'returned mail', 'vacation'
  ];
  
  if (blacklistSubjectPatterns.some(pattern => subject.includes(pattern))) {
    return { isSpam: true, reason: `Subject contains blacklisted keyword "${subject}"` };
  }

  // 3. Check Auto-Submitted and Precedence headers
  if (parsed.headers) {
    // In mailparser, headers is a Map
    const autoSubmitted = parsed.headers.get('auto-submitted');
    if (autoSubmitted) {
      const val = String(autoSubmitted).toLowerCase();
      if (val && val !== 'no') {
        return { isSpam: true, reason: `Auto-Submitted header is "${val}"` };
      }
    }
    const precedence = parsed.headers.get('precedence');
    if (precedence) {
      const val = String(precedence).toLowerCase();
      if (['bulk', 'junk', 'list'].includes(val)) {
        return { isSpam: true, reason: `Precedence header is "${val}"` };
      }
    }
  }

  return { isSpam: false };
}


/**
 * Sends a registration acknowledgement email back to the customer.
 */
async function sendAutomatedReply(recipientEmail, contactName, enquiryId, extracted) {
  const smtpHost = process.env.SMTP_HOST || 'mail.petrovalves.co.in';
  const smtpPort = parseInt(process.env.SMTP_PORT || 465, 10);
  const smtpUser = process.env.SMTP_USER || 'ai@petrovalvesco.in';
  const smtpPass = process.env.SMTP_PASS || 'Ai@@27042026';

  console.log(`[Email Bot] Preparing outgoing reply via SMTP ${smtpHost}:${smtpPort} as ${smtpUser}...`);
  
  const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465,
    auth: {
      user: smtpUser,
      pass: smtpPass
    }
  });

  const mailOptions = {
    from: `"Petro Valve AI Assistant" <${smtpUser}>`,
    to: recipientEmail,
    subject: `Acknowledgement: Enquiry Registered [Ref: ${enquiryId}]`,
    text: `Dear ${contactName},

Thank you for your enquiry. We have successfully registered your request in our system under Reference ID: ${enquiryId}.

Here are the details we recorded:
- Product Description: ${extracted.productDescription}
- Product Category: ${extracted.productCategory}
- Quantity: ${extracted.quantity} ${extracted.unit}
- Priority: ${extracted.priority}

Our sales team is preparing your quotation and will contact you shortly.

Best regards,
Petro Valve AI Team
ai@petrovalvesco.in`,
    html: `
      <div style="font-family: 'Helvetica Neue', Arial, sans-serif; padding: 25px; color: #334155; line-height: 1.6; max-width: 600px; border: 1px solid #e2e8f0; border-radius: 16px;">
        <div style="border-bottom: 2px solid #2563eb; padding-bottom: 15px; margin-bottom: 20px;">
          <h2 style="color: #1e3a8a; margin: 0; font-size: 20px;">Petro Valve AI Assistant</h2>
          <span style="font-size: 11px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em;">Auto-Registration</span>
        </div>
        <p>Dear <strong>${contactName}</strong>,</p>
        <p>Thank you for reaching out to Petro Valve. We have successfully received and registered your enquiry under Reference ID: <strong style="color: #2563eb; background-color: #eff6ff; padding: 2px 8px; border-radius: 4px;">${enquiryId}</strong>.</p>
        
        <div style="background-color: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 15px; margin: 20px 0;">
          <h4 style="margin-top: 0; color: #475569; font-size: 13px; text-transform: uppercase; letter-spacing: 0.05em;">Enquiry Details:</h4>
          <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
            <tr>
              <td style="padding: 6px 0; color: #64748b; font-weight: 500; width: 140px;">Product Details:</td>
              <td style="padding: 6px 0; color: #0f172a; font-weight: bold;">${extracted.productDescription}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b; font-weight: 500;">Product Category:</td>
              <td style="padding: 6px 0; color: #0f172a; font-weight: bold;">${extracted.productCategory}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b; font-weight: 500;">Quantity:</td>
              <td style="padding: 6px 0; color: #0f172a; font-weight: bold;">${extracted.quantity} ${extracted.unit}</td>
            </tr>
            <tr>
              <td style="padding: 6px 0; color: #64748b; font-weight: 500;">Priority Class:</td>
              <td style="padding: 6px 0; color: #0f172a; font-weight: bold;">${extracted.priority}</td>
            </tr>
          </table>
        </div>
        
        <p>Our sales team is already preparing your commercial quotation and will get in touch with you shortly.</p>
        
        <p style="margin-top: 30px; font-size: 12px; color: #94a3b8; border-top: 1px solid #slate-100; pt-15;">
          Best regards,<br/>
          <strong>Petro Valve Sales Team</strong><br/>
          <a href="mailto:${smtpUser}" style="color: #2563eb; text-decoration: none;">${smtpUser}</a>
        </p>
      </div>
    `
  };

  const info = await transporter.sendMail(mailOptions);
  console.log(`[Email Bot] Outgoing reply sent: ${info.messageId}`);
}

/**
 * Handles the creation of Customer, Enquiry, Task and Notification from a single email.
 */
async function processEmailMessage(parsed) {
  const fromText = parsed.from?.text || '';
  const senderEmail = parsed.from?.value?.[0]?.address || extractEmail(fromText);
  const senderName = parsed.from?.value?.[0]?.name || fromText.split('<')[0].replace(/"/g, '').trim() || 'Email Sender';
  const subject = parsed.subject || 'No Subject';
  const bodyText = parsed.text || parsed.html?.replace(/<[^>]+>/g, '') || '';

  // Extract structured lead via AI
  const extracted = await aiService.extractEnquiryDetails(bodyText, { from: fromText, subject });

  // Check if AI classified it as an actual business enquiry
  if (extracted.isEnquiry === false) {
    console.log(`[Email Bot] Email from ${senderEmail} classified by AI as NOT a business enquiry. Skipping DB insertion.`);
    return;
  }

  // 1. Find or create Customer
  let customer = await Customer.findOne({ 
    $or: [
      { emailAddress: senderEmail.toLowerCase() },
      { alternateEmail: senderEmail.toLowerCase() }
    ]
  });

  if (!customer) {
    console.log(`[Email Bot] Customer not found. Auto-creating customer for ${senderEmail}`);
    customer = await Customer.create({
      companyName: extracted.companyName || 'Individual Customer',
      primaryContactName: extracted.primaryContactName || senderName,
      mobileNumber: extracted.mobileNumber || '0000000000',
      emailAddress: senderEmail.toLowerCase(),
      customerId: `CUS-${Date.now().toString().slice(-6)}`,
      sourceChannel: 'Email'
    });
  }

  // 2. Find a default user to assign (Super Admin / Director / Sales)
  const defaultAgent = await User.findOne({ is_active: true, role: { $in: ['SUPER_ADMIN', 'DIRECTOR', 'SA', 'DIR'] } }) || await User.findOne({ is_active: true });
  const agentId = defaultAgent ? defaultAgent._id : null;

  // 3. Generate sequential Enquiry ID
  const year = new Date().getFullYear();
  const month = String(new Date().getMonth() + 1).padStart(2, '0');
  const prefix = `ENQ-${year}-${month}-`;
  const seq = await getNextSequenceValue(prefix);
  const enquiryId = `${prefix}${String(seq).padStart(4, '0')}`;

  // 4. Create Enquiry
  const enquiry = await Enquiry.create({
    enquiryId,
    customer: customer._id,
    sourceChannel: 'Email',
    emailAccount: 'info@', // Default account designation
    contactPerson: extracted.primaryContactName || customer.primaryContactName,
    contactMobile: extracted.mobileNumber || customer.mobileNumber,
    contactEmail: senderEmail.toLowerCase(),
    productCategory: extracted.productCategory,
    productDescription: extracted.productDescription,
    quantity: extracted.quantity,
    unit: extracted.unit,
    standardCode: extracted.standardCode,
    specialRequirements: extracted.specialRequirements,
    priority: extracted.priority,
    assignedTo: agentId,
    createdBy: agentId,
    status: 'New'
  });

  console.log(`[Email Bot] Auto-created Enquiry ${enquiryId} for Customer ${customer.companyName}`);

  // 5. Create System Follow-up Task and Notification
  if (agentId) {
    const due = new Date();
    due.setDate(due.getDate() + 1); // Due tomorrow
    
    await Task.create({
      title: `Review Email Enquiry ${enquiryId}`,
      description: `System generated task to review and follow up with the customer regarding: ${extracted.productDescription}.`,
      dueDate: due,
      priority: extracted.priority === 'Urgent' ? 'High' : 'Medium',
      status: 'To Do',
      assignedTo: agentId,
      createdBy: agentId,
      linkedEnquiry: enquiry._id
    });

    await createNotification({
      user_id: agentId,
      type: 'ENQUIRY_ASSIGNED',
      title: '📩 New Lead from Email',
      message: `Enquiry ${enquiryId} auto-created for ${customer.companyName} (${extracted.productCategory}).`,
      related_id: enquiry._id
    });
  }

  // 6. Send Automated SMTP Reply to Customer
  try {
    await sendAutomatedReply(senderEmail, extracted.primaryContactName || senderName, enquiryId, extracted);
  } catch (smtpErr) {
    console.error(`[Email Bot] Failed to send SMTP reply to ${senderEmail}:`, smtpErr.message);
  }
}

/**
 * Checks the inbox for unseen emails, parses them, and runs extraction/replies.
 */
async function checkEmails() {
  if (isProcessing) {
    console.log('[Email Bot] Previous execution is still processing. Skipping...');
    return;
  }
  isProcessing = true;

  const imapHost = process.env.IMAP_HOST || 'mail.petrovalves.co.in';
  const imapPort = parseInt(process.env.IMAP_PORT || 993, 10);
  const imapUser = process.env.IMAP_USER || 'ai@petrovalvesco.in';
  const imapPass = process.env.IMAP_PASS || 'Ai@@27042026';

  const client = new ImapFlow({
    host: imapHost,
    port: imapPort,
    secure: true,
    auth: {
      user: imapUser,
      pass: imapPass
    },
    logger: false,
    connectionTimeout: 10000,
    greetingTimeout: 10000
  });

  try {
    console.log(`[Email Bot] Connecting to IMAP mailbox: ${imapHost}:${imapPort} as ${imapUser}...`);
    await client.connect();
    
    // Lock INBOX folder to perform operations
    let lock = await client.getMailboxLock('INBOX');
    try {
      // Find UIDs of all unseen (unread) messages
      const uids = await client.search({ seen: false }, { uid: true });
      console.log(`[Email Bot] Found ${uids.length} unseen email(s) in INBOX.`);

      for (const uid of uids) {
        console.log(`[Email Bot] Fetching raw message source for UID ${uid}...`);
        try {
          const emailStream = await client.download(uid, null, { uid: true });
          const parsed = await simpleParser(emailStream.content);
          
          // Check if auto-generated, bounce, or spam/notification
          const spamCheck = isAutoGeneratedOrSpam(parsed);
          if (spamCheck.isSpam) {
            console.log(`[Email Bot] Skipping UID ${uid}: ${spamCheck.reason}`);
            // Mark the email as SEEN (read) so we don't process it again
            await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
            continue;
          }
          
          // Process the parsed message
          await processEmailMessage(parsed);
          
          // Mark the email as SEEN (read)
          await client.messageFlagsAdd(uid, ['\\Seen'], { uid: true });
          console.log(`[Email Bot] Successfully processed and marked UID ${uid} as SEEN.`);
        } catch (msgErr) {
          console.error(`[Email Bot] Failed to process message UID ${uid}:`, msgErr);
        }
      }
    } finally {
      // Release lock on INBOX
      lock.release();
    }
    
    await client.logout();
    console.log('[Email Bot] Logged out from IMAP box successfully.');
  } catch (err) {
    console.error('[Email Bot] Connection/processing failed:', err.message);
  } finally {
    isProcessing = false;
  }
}

/**
 * Starts the background polling worker.
 * Checks the inbox immediately, then polls every 1 minute.
 */
exports.start = () => {
  if (intervalId) {
    console.log('[Email Bot] Worker already running.');
    return;
  }
  
  console.log('[Email Bot] Starting background AI email processing service (1-minute polling interval)...');
  
  // Initial run
  checkEmails();
  
  // Setup interval
  intervalId = setInterval(checkEmails, 60000);
};

/**
 * Stops the background worker.
 */
exports.stop = () => {
  if (intervalId) {
    clearInterval(intervalId);
    intervalId = null;
    console.log('[Email Bot] Background worker stopped.');
  }
};

// Export internal functions for unit testing and manual triggers
exports.processEmailMessage = processEmailMessage;
exports.checkEmails = checkEmails;

